// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/App.tsx";
import * as $1 from "./routes/Datasets.tsx";
import * as $2 from "./routes/ExperimentsOverview.tsx";
import * as $3 from "./routes/Interfaces.ts";
import * as $4 from "./routes/Models.tsx";
import * as $5 from "./routes/NavBar.tsx";
import * as $6 from "./routes/ResultDisplay.tsx";
import * as $7 from "./routes/Results.tsx";
import * as $8 from "./routes/Trainers.tsx";
import * as $9 from "./routes/api/joke.ts";
import * as $10 from "./routes/experiments/[name].tsx";
import * as $11 from "./routes/index.tsx";
import * as $$0 from "./islands/App.tsx";
import * as $$1 from "./islands/ExperimentView.tsx";

const manifest = {
  routes: {
    "./routes/App.tsx": $0,
    "./routes/Datasets.tsx": $1,
    "./routes/ExperimentsOverview.tsx": $2,
    "./routes/Interfaces.ts": $3,
    "./routes/Models.tsx": $4,
    "./routes/NavBar.tsx": $5,
    "./routes/ResultDisplay.tsx": $6,
    "./routes/Results.tsx": $7,
    "./routes/Trainers.tsx": $8,
    "./routes/api/joke.ts": $9,
    "./routes/experiments/[name].tsx": $10,
    "./routes/index.tsx": $11,
  },
  islands: {
    "./islands/App.tsx": $$0,
    "./islands/ExperimentView.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
